
### Post a deck group

POST http://localhost:8080/deckgroup
Content-Type: application/json

{
  "name": "Bonjour!",
  "description": "This is a sunny day"
}


### Get all the deck groups
GET http://localhost:8080/deckgroup
